name: Stage Deploy ENT Address
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened]

jobs:
  master:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm i
      - run: node ./script.js
